config/routes.rb
Rails.application.routes.draw do
  resources :experiences, :domaines, :langues, :cursus, :offres
  resources :postulers, except: :new
  root to: 'pages#index'
  get 'team', to: 'pages#team'
  get 'who', to: 'pages#who'
  devise_for :users, path: 'users', :controllers => {
  	:registrations => 'users/registrations',
  }
  devise_for :entreprises, path: 'entreprises', :controllers => {
    :registrations => 'entreprises/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cursu.rb
class Cursu < ApplicationRecord
  belongs_to :user
end

app/controllers/cursus_controller.rb
class CursusController < ApplicationController
  before_action :set_cursu, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /cursus
  # GET /cursus.json
  def index
    @cursus = Cursu.all
  end

  # GET /cursus/1
  # GET /cursus/1.json
  def show
  end

  # GET /cursus/new
  def new
    @cursu = Cursu.new
  end

  # GET /cursus/1/edit
  def edit
  end

  # POST /cursus
  # POST /cursus.json
  def create
    @cursu = Cursu.new(cursu_params)

    respond_to do |format|
      if @cursu.save
        format.html { redirect_to @cursu, notice: 'Cursu was successfully created.' }
        format.json { render :show, status: :created, location: @cursu }
      else
        format.html { render :new }
        format.json { render json: @cursu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursus/1
  # PATCH/PUT /cursus/1.json
  def update
    respond_to do |format|
      if @cursu.update(cursu_params)
        format.html { redirect_to @cursu, notice: 'Cursu was successfully updated.' }
        format.json { render :show, status: :ok, location: @cursu }
      else
        format.html { render :edit }
        format.json { render json: @cursu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursus/1
  # DELETE /cursus/1.json
  def destroy
    @cursu.destroy
    respond_to do |format|
      format.html { redirect_to cursus_url, notice: 'Cursu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cursu
      @cursu = Cursu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cursu_params
      params.require(:cursu).permit(:ecole, :annee_debut, :annee_fin, :diplome, :user_id)
    end
end

app/helpers/cursus_helper.rb
module CursusHelper
end

app/views/cursus/_form.html.erb
<%= form_with(model: cursu, local: true) do |form| %>
  <% if cursu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cursu.errors.count, "error") %> prohibited this cursu from being saved:</h2>

      <ul>
      <% cursu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ecole %>
    <%= form.text_field :ecole %>
  </div>

  <div class="field">
    <%= form.label :annee_debut %>
    <%= form.date_select :annee_debut %>
  </div>

  <div class="field">
    <%= form.label :annee_fin %>
    <%= form.date_select :annee_fin %>
  </div>

  <div class="field">
    <%= form.label :diplome %>
    <%= form.text_field :diplome %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cursus/edit.html.erb
<h1>Editing Cursu</h1>

<%= render 'form', cursu: @cursu %>

<%= link_to 'Show', @cursu %> |
<%= link_to 'Back', cursus_path %>

app/views/cursus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cursus</h1>

<table>
  <thead>
    <tr>
      <th>Ecole</th>
      <th>Annee debut</th>
      <th>Annee fin</th>
      <th>Diplome</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursus.each do |cursu| %>
      <tr>
        <td><%= cursu.ecole %></td>
        <td><%= cursu.annee_debut %></td>
        <td><%= cursu.annee_fin %></td>
        <td><%= cursu.diplome %></td>
        <td><%= cursu.user %></td>
        <td><%= link_to 'Show', cursu %></td>
        <td><%= link_to 'Edit', edit_cursu_path(cursu) %></td>
        <td><%= link_to 'Destroy', cursu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cursu', new_cursu_path %>

app/views/cursus/new.html.erb
<h1>New Cursu</h1>

<%= render 'form', cursu: @cursu %>

<%= link_to 'Back', cursus_path %>

app/views/cursus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ecole:</strong>
  <%= @cursu.ecole %>
</p>

<p>
  <strong>Annee debut:</strong>
  <%= @cursu.annee_debut %>
</p>

<p>
  <strong>Annee fin:</strong>
  <%= @cursu.annee_fin %>
</p>

<p>
  <strong>Diplome:</strong>
  <%= @cursu.diplome %>
</p>

<p>
  <strong>User:</strong>
  <%= @cursu.user %>
</p>

<%= link_to 'Edit', edit_cursu_path(@cursu) %> |
<%= link_to 'Back', cursus_path %>