config/routes.rb
Rails.application.routes.draw do
  resources :experiences, :domaines, :langues, :cursus, :offres
  resources :postulers, except: :new
  root to: 'pages#index'
  get 'team', to: 'pages#team'
  get 'who', to: 'pages#who'
  devise_for :users, path: 'users', :controllers => {
  	:registrations => 'users/registrations',
  }
  devise_for :entreprises, path: 'entreprises', :controllers => {
    :registrations => 'entreprises/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/langue.rb
class Langue < ApplicationRecord
  belongs_to :user
end

app/controllers/langues_controller.rb
class LanguesController < ApplicationController
  before_action :set_langue, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /langues
  # GET /langues.json
  def index
    @langues = Langue.all
  end

  # GET /langues/1
  # GET /langues/1.json
  def show
  end

  # GET /langues/new
  def new
    @langue = Langue.new
  end

  # GET /langues/1/edit
  def edit
  end

  # POST /langues
  # POST /langues.json
  def create
    @langue = Langue.new(langue_params)

    respond_to do |format|
      if @langue.save
        format.html { redirect_to @langue, notice: 'Langue was successfully created.' }
        format.json { render :show, status: :created, location: @langue }
      else
        format.html { render :new }
        format.json { render json: @langue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /langues/1
  # PATCH/PUT /langues/1.json
  def update
    respond_to do |format|
      if @langue.update(langue_params)
        format.html { redirect_to @langue, notice: 'Langue was successfully updated.' }
        format.json { render :show, status: :ok, location: @langue }
      else
        format.html { render :edit }
        format.json { render json: @langue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /langues/1
  # DELETE /langues/1.json
  def destroy
    @langue.destroy
    respond_to do |format|
      format.html { redirect_to langues_url, notice: 'Langue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_langue
      @langue = Langue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def langue_params
      params.require(:langue).permit(:langue, :niveau, :user_id)
    end
end

app/helpers/langues_helper.rb
module LanguesHelper
end

app/views/langues/_form.html.erb
<%= form_with(model: langue, local: true) do |form| %>
  <% if langue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(langue.errors.count, "error") %> prohibited this langue from being saved:</h2>

      <ul>
      <% langue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :langue %>
    <%= form.text_field :langue %>
  </div>

  <div class="field">
    <%= form.label :niveau %>
    <%= form.text_field :niveau %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/langues/edit.html.erb
<h1>Editing Langue</h1>

<%= render 'form', langue: @langue %>

<%= link_to 'Show', @langue %> |
<%= link_to 'Back', langues_path %>

app/views/langues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Langues</h1>

<table>
  <thead>
    <tr>
      <th>Langue</th>
      <th>Niveau</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @langues.each do |langue| %>
      <tr>
        <td><%= langue.langue %></td>
        <td><%= langue.niveau %></td>
        <td><%= langue.user %></td>
        <td><%= link_to 'Show', langue %></td>
        <td><%= link_to 'Edit', edit_langue_path(langue) %></td>
        <td><%= link_to 'Destroy', langue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Langue', new_langue_path %>

app/views/langues/new.html.erb
<h1>New Langue</h1>

<%= render 'form', langue: @langue %>

<%= link_to 'Back', langues_path %>

app/views/langues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Langue:</strong>
  <%= @langue.langue %>
</p>

<p>
  <strong>Niveau:</strong>
  <%= @langue.niveau %>
</p>

<p>
  <strong>User:</strong>
  <%= @langue.user %>
</p>

<%= link_to 'Edit', edit_langue_path(@langue) %> |
<%= link_to 'Back', langues_path %>