config/routes.rb
Rails.application.routes.draw do
  resources :experiences, :domaines, :langues, :cursus, :offres
  resources :postulers, except: :new
  root to: 'pages#index'
  get 'team', to: 'pages#team'
  get 'who', to: 'pages#who'
  devise_for :users, path: 'users', :controllers => {
  	:registrations => 'users/registrations',
  }
  devise_for :entreprises, path: 'entreprises', :controllers => {
    :registrations => 'entreprises/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
    can :read, Offre, User
    
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cursu.rb
class Cursu < ApplicationRecord
  belongs_to :user
end

app/models/domaine.rb
class Domaine < ApplicationRecord
  belongs_to :user
end

app/models/entreprise.rb
class Entreprise < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
end

app/models/langue.rb
class Langue < ApplicationRecord
  belongs_to :user
end

app/models/offre.rb
class Offre < ApplicationRecord
  belongs_to :domaine
  belongs_to :user
end

app/models/postuler.rb
class Postuler < ApplicationRecord
  belongs_to :user
  belongs_to :offre
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.from_facebook(auth)
  	where(facebook_id: auth.uid).first_or_create do |user|
  		user.email = auth.info.email
  		user.password = Devise.friendly_token[0, 20]
  		user.skip_confirmation!
  	end
  end

  def self.from_google(auth)
  	where(google_oauth2_id: auth.uid).first_or_create do |user|
  		user.email = auth.info.email
  		user.password = Devise.friendly_token[0, 20]
  		user.skip_confirmation!
  	end
  end

end

app/controllers/cursus_controller.rb
class CursusController < ApplicationController
  before_action :set_cursu, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /cursus
  # GET /cursus.json
  def index
    @cursus = Cursu.all
  end

  # GET /cursus/1
  # GET /cursus/1.json
  def show
  end

  # GET /cursus/new
  def new
    @cursu = Cursu.new
  end

  # GET /cursus/1/edit
  def edit
  end

  # POST /cursus
  # POST /cursus.json
  def create
    @cursu = Cursu.new(cursu_params)

    respond_to do |format|
      if @cursu.save
        format.html { redirect_to @cursu, notice: 'Cursu was successfully created.' }
        format.json { render :show, status: :created, location: @cursu }
      else
        format.html { render :new }
        format.json { render json: @cursu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursus/1
  # PATCH/PUT /cursus/1.json
  def update
    respond_to do |format|
      if @cursu.update(cursu_params)
        format.html { redirect_to @cursu, notice: 'Cursu was successfully updated.' }
        format.json { render :show, status: :ok, location: @cursu }
      else
        format.html { render :edit }
        format.json { render json: @cursu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursus/1
  # DELETE /cursus/1.json
  def destroy
    @cursu.destroy
    respond_to do |format|
      format.html { redirect_to cursus_url, notice: 'Cursu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cursu
      @cursu = Cursu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cursu_params
      params.require(:cursu).permit(:ecole, :annee_debut, :annee_fin, :diplome, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	
  end

  def team
    
  end

  def who
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cursus_helper.rb
module CursusHelper
end

app/helpers/domaines_helper.rb
module DomainesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/langues_helper.rb
module LanguesHelper
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/postulers_helper.rb
module PostulersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boulot</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
      <a class="navbar-brand text-danger" href="/">BOULOT</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">ACCUEIL<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">COMMENT ÇA MARCHE</a>
          </li>

          <!-- <li class="nav-item">
            <a class="nav-link" href="<%= offres_path %>">Offre</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= domaines_path %>">Domaine</a>
          </li> -->

          <li class="nav-item">
            <a class="nav-link" href="team">TEAM</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#!">CONTACT</a>
          </li>
          <% if signed_in? %>
            <li class="nav-item">
              <%= link_to  "DECONNEXION", destroy_user_session_path, method: :DELETE, data: { confirm:'Voulez-vous vous deconnecter ?' }, :class => 'nav-link' %>
            </li>
          <% end %>
          <%if current_user %>
            <li class="nav-item">
              <%= link_to  "OFFRES", offres_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to  "DOMAINES", domaines_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to  "CURSUS", cursus_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to  "LANGUES", langues_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to  "EXPERIENCE", experiences_path, :class => 'nav-link' %>
            </li>
          <% end %>
          <% if !signed_in? %>
            <li class="nav-item ">
              <%= link_to  "CONNEXION", who_path, :class => 'nav-link' %>
            </li>
          <% end %>
          </ul>
      </div>
    </nav>

    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

    <main class="yield">
      <%= yield %>
    </main>
   
    <!-- <footer>
      <p>BOULOT &copy 2019 | Tous droits réservés.</p>
    </footer> -->

    <!-- Scripts JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>
    <script>
      //import Typed from 'typed.js';
  
      var options = {
          strings: ["connecte les personnes entre elles", "repousse les barrières du chômage",
          "offre de la main d'oeuvre qualifiée aux entreprises", "trouve un boulot à tous"],
          typeSpeed: 40,
          backSpeed: 30,
          fadeOut: true,
          cursorChar: '_',
          smartBackspace: true,
          loop: true
      }
  
      var typed = new Typed("#element", options);
  </script>
    <!-- //Scripts JS -->
  </body>
</html>

app/views/pages/index.html.erb
<!-- Header section -->
<section class="home-pg">
    <div class="container">
        <div class="header-text">
            <h1 class="text-danger" style="font-size:60px; font-weight:bold;">BOULOT</h1>
            <h1 class="text-white" id="element" style="font-size:60px; font-weight:bold;"></h1>  
        </div><br><br><br>
        <!-- <div class="btn-position">
            <a class="btn btn-danger btn-lg" href="#" role="button">Démarrez ici</a>
        </div>  -->
    </div>
</section>
<!-- Fin Header section -->

<!-- Description section -->
<section class="description">
    <div class="container">
        <h1 class="text-secondary" style="font-size:58px; font-weight:bold;">
            Boulot connecte les personnes entre elles afin de créer de la valeur. Vous avez des compétences
            à faire valoir ? Commencez à être rémunéré pour cela.
        </h1>
    </div>
</section>
<!-- Fin Description section -->

<!-- Users section -->
<section class="users">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="text-secondary" style="font-weight:bold;font-size:50px;">
                    Commencez une expérience nouvelle du travail
                </h1><br>
                <a href="who" class="btn btn-lg btn-danger text-white">DÉMARREZ ICI &nbsp;></a>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
</section>
<!-- Fin Users section -->

<!-- CTA section -->
<section class="cta">
    <div class="container cta-content">
        <div>
            <h1 class="text-white" style="font-weight:bold;font-size:50px;">
                Soyez informer de nos activités
            </h1><br>
            <form action="">
                <div class="col-auto">
                    <label class="sr-only" for="inlineFormInputGroup">Adresse e-mail</label>
                    <input type="text" class="form-control newsletter" id="inlineFormInputGroup" placeholder="Adresse e-mail" style="width:70vh">
                    <input type="submit" value="Inscription" class="btn btn-danger newsletter">
                </div>
            </form>
        </div>
    </div>
</section>
<!-- Fin CTA section -->

app/views/pages/team.html.erb
<h1>LA TEAM</h1>

app/views/pages/who.html.erb
<section class="who">
    <div class="container who-content">
        <div class="row">
            <!-- Particuliers section -->
            <div class="col particuliers">
                <p class="text-danger"><b>BOULOT</b></p>
                <p class="text-danger" style="font-size:40px;">Standard</p><br>
                <p class="text-white" style="font-size:16px;"><b>Pour élèves, étudiants, jeunes diplomés,<br> chômeurs, salariés, ouvriers et demandeurs d'emploi</b></p><br>
                <p class="text-white" style="font-size:16px;">Mettez vos compétences et savoir-faire au service <br> d'autres personnes et soyez rémunérés.</p><br>
                <a href="<%= new_user_registration_path %>" class="btn btn-lg btn-danger text-white">INSCRIPTION &nbsp;></a>
            </div>
            <!-- Fin Particuliers section -->
    
            <!-- Entreprises section -->
            <div class="col entreprises">
                <p class="text-danger"><b>BOULOT</b></p>
                <p class="text-danger" style="font-size:40px;">Business</p><br>
                <p class="text-white" style="font-size:16px;"><b>Pour startups, PME, entreprises et firmes</b></p><br>
                <p class="text-white" style="font-size:16px;">Trouvez les compétences et la main d'oeuvre<br> dont vous avez besoin pour des besoins ponctuels ou à long terme. </p><br>
                <a href="<%= new_entreprise_registration_path %>" class="btn btn-lg btn-danger text-white">INSCRIPTION &nbsp;></a>
            </div>
            <!-- Fin Entreprises section -->
        </div>
    </div>
</section>